name: GitHub Actions Build and Deploy Demo
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false
            - name: Install and Build
              run: |
                  npm install
                  npm run build

            - name: Build and push Docker image
              run: |
                  pwd
                  ls
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker build -t taoism-admin  .
                  docker tag taoism-admin ${{ secrets.DOCKER_REPOSITORY }}
                  docker push ${{ secrets.DOCKER_REPOSITORY }}

            - name: ssh server run docker image
              uses: appleboy/ssh-action@v0.1.7
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: ${{ secrets.SERVER_USRENAME }}
                  # password: ${{ secrets.SERVER_PASSWORD  }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      whoami
                      cd ~
                      sh frontDeploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
