name: GitHub Actions Build and Deploy Demo
on:
    push:
        tags:
            - 'v*'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      release
                  draft: false
                  prerelease: false

            - name: Install and Build
              run: |
                  npm install
                  npm run build

            - name: Build and push Docker image
              run: |
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker build -t v1.0.0  .
                  docker tag v1.0.0 ${{ secrets.DOCKER_REPOSITORY }}
                  docker push ${{ secrets.DOCKER_REPOSITORY }}

            - name: ssh server run docker image
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      whoami
                      cd ~
                      sh frontDeploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
