name: GitHub Actions Build and Deploy Demo
on:    
    push:
        branches:
              — '*'

jobs:
    build:

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Install and Build
              run: |
                  npm install
                  npm run build
                
            — name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            — name: Build and push
                uses: docker/build-push-action@v2
                with:
                  context: .
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}


            - name: ssh server run docker image
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_IP }}
                  username: root
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script: |
                      whoami
                      cd ~
                      sh frontDeploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
