name: Docker Image CI

on:
    push:
        branches: ['main']
    # pull_request:
    #     branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push Docker image
              run: |
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: push
                id: docker_build
              uses: docker/build-push-action@v2
              with:
                push: true
                tags: f5l5y5/taoism-admin:latest

            # - name: ssh server run docker image
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: ${{ secrets.SERVER_IP }}
            #       username: root
            #       password: ${{ secrets.SERVER_PASSWORD }}
            #       script: |
            #           whoami
            #           cd ~
            #           sh frontDeploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
