name: Docker Image CI

on:
    push:
        branches: ['main']
    # pull_request:
    #     branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push Docker image
              run: |
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker build -t taosim-admin --tag v0.0.6 .
                  docker push f5l5y5:taosim-admin:v0.0.6

            # - name: ssh server run docker image
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: ${{ secrets.SERVER_IP }}
            #       username: root
            #       password: ${{ secrets.SERVER_PASSWORD }}
            #       script: |
            #           whoami
            #           cd ~
            #           sh frontDeploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
